#!/bin/bash

while IFS= read -n1 c
do
    case $c in
        [a-zA-Z0-9.~_-])
            printf "$c"
            ;;
        *)
            printf '%s' "$c" | \
                xxd -p -c1 | \
                while read c;
                do
                    printf '%%%s' "$c";
                done
            ;;
    esac
done
